service: resources
frameworkVersion: ">=2.48.1"
custom:
  bucket: img-rec
  crawlerqueue: ImgRecQueue
  analysisqueue: ImgRecAnlQueue
  region: 'eu-west-1'
  accountid: 203212890819 #changeme

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: 'eu-west-1'

resources:
  Resources:
    WebAppS3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:custom.bucket}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebAppS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.bucket}/*

    ImgRecQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.crawlerqueue}

    ImgRecAnlQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.analysisqueue}
